### ISSUE TITLE
Whisper instructions

### ISSUE THREAD

**Issue by Dinsmoor** [reasv/panoptikon#5]
This is just from the perspective of a guy trying to use the thing:

On fresh install with `poetry install --with inference` - attempting to run the tiny.en whisper data extraction results in `ModuleNotFoundError: No module named 'av'` error.

Updated pyproject.toml with `av = "^14.0.1"` and then locked it, did another poetry install.

Attempting to run a whisper model after this results in:
```
Unable to load any of {libcudnn_ops.so.9.1.0, libcudnn_ops.so.9.1, libcudnn_ops.so.9, libcudnn_ops.so}
Invalid handle. Cannot load symbol cudnnCreateTensorDescriptor
```

The readme told me to expect this: However, going to the nvidia page and get the cudnn 8 package, what are we supposed to do with this? There is no makefile or compilation instructions there.

When installing my distribution's nvidia-libcudnn package, it automatically compiled the contents of "cudnn-linux-x86_64-8.9.2.26_cuda12-archive.tar.xz"  - but I still get the same error as above.

What am I doing wrong? Some other models work fine (DocTR)

Just a note to consider as an alternative: https://github.com/ggerganov/whisper.cpp and https://github.com/aarnphm/whispercpp (python bindings)

Whisper.cpp is very fast btw.

**Comment by Dinsmoor** [comment]
I was able to fix this by running it like:

`LD_LIBRARY_PATH='cudnn/bin/' poetry run panoptikon`

after making sure the the ./cudnn/bin directory had the proper contents:

```shell
libcudnn_adv.so           libcudnn_engines_precompiled.so                libcudnn_graph.so               libcudnn_ops.so
libcudnn_adv.so.9         libcudnn_engines_precompiled.so.9              libcudnn_graph.so.9             libcudnn_ops.so.9
libcudnn_adv.so.9.6.0     libcudnn_engines_precompiled.so.9.6.0          libcudnn_graph.so.9.6.0         libcudnn_ops.so.9.6.0
libcudnn_adv_static.a     libcudnn_engines_precompiled_static.a          libcudnn_graph_static.a         libcudnn_ops_static.a
libcudnn_adv_static_v9.a  libcudnn_engines_precompiled_static_v9.a       libcudnn_graph_static_v9.a      libcudnn_ops_static_v9.a
libcudnn_cnn.so           libcudnn_engines_runtime_compiled.so           libcudnn_heuristic.so           libcudnn.so
libcudnn_cnn.so.9         libcudnn_engines_runtime_compiled.so.9         libcudnn_heuristic.so.9         libcudnn.so.9
libcudnn_cnn.so.9.6.0     libcudnn_engines_runtime_compiled.so.9.6.0     libcudnn_heuristic.so.9.6.0     libcudnn.so.9.6.0
libcudnn_cnn_static.a     libcudnn_engines_runtime_compiled_static.a     libcudnn_heuristic_static.a
libcudnn_cnn_static_v9.a  libcudnn_engines_runtime_compiled_static_v9.a  libcudnn_heuristic_static_v9.a
```

Please update the readme or set the os.environment to the proper LD path, if it exists.

Another place where these libraries exist on a standard panoptikon install is: `~/.cache/pypoetry/virtualenvs/panoptikon-[the unique id]-py3.12/lib/python3.12/site-packages/nvidia/cudnn/lib/` but panoptikon can't find them for some reason.

**Comment by reasv** [comment]
Can it find them when you set the env variable manually?

**Comment by Dinsmoor** [comment]
No, when setting it like: `LD_LIBRARY_PATH='~/.cache/pypoetry/virtualenvs/panoptikon-PlTED-NR-py3.12/lib/python3.12/site-packages/nvidia/cudnn/lib/' poetry run panoptikon` it does not work.

**Comment by reasv** [comment]
Are you sure the files there aren't the problem themselves? Try directly copying the files in ~/.cache/pypoetry/virtualenvs/panoptikon-PlTED-NR-py3.12/lib/python3.12/site-packages/nvidia/cudnn/lib/ into the cudnn/bin folder
If it works with the same files, it's the location. If it doesn't, it's the files

**Comment by Dinsmoor** [comment]
`cp ~/.cache/pypoetry/virtualenvs/panoptikon-PlTED-NR-py3.12/lib/python3.12/site-packages/nvidia/cudnn/lib/* cudnn/bin2`
`LD_LIBRARY_PATH='cudnn/bin2/' poetry run panoptikon`

Whisper works fine.
